" Use Vim settings, not Vi
set nocompatible

" General {
  " Set background to dark
  set background=dark
  " Set Mouse to always on
  set mouse=a
  " Hide mouse cursor while typing
  set mousehide
" }

" Allow backspacing in insert mode
set backspace=indent,eol,start

" --------------
" Backup settings
" --------------
" Store backups in a central location
" Using trailing double slashes enables a feature to avoid name collisions
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//

" Keep 5000 lines of command line history
set history=5001

" Show the cursor position all the time
set ruler

" Reload files
 set autoread


" Do incremental searching
set incsearch

" Turn on syntax highlighting and highlighted search
syntax on
set hlsearch

" Show existing tab with 4 space width
set tabstop=4
" When indenting with '>', use 4 space width
set shiftwidth=4
" When pressing tab, insert 4 spaces
set expandtab
" Let backspace delete indent
set softtabstop=4

" Highlight the background past 80 characters
au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)

" Always display the status line
set laststatus=2

" Highlight training whitespace characters in red
" Don't highlight while in insert mode
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" always set autoindenting on
set autoindent

" copy the previous indentation on autoindenting
set copyindent

" --------------
" UI Setup
" --------------
" Turn on line numbers
set number
" Display incomplete commands
set showcmd
" Detect the type of file and appropriate indentation
filetype plugin indent on
" Set visual autocomplete for command menu
set wildmenu
" Draw a horizontal highlight for the current line
" Highlight the current line
set cursorline
" Set the cursorline colors
highlight CursorLine term=bold cterm=bold ctermbg=235
" Remove highlight when the window loses focus
autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline

" --------------
" Search Settings
" --------------
set incsearch   " show search matches as you type
set ignorecase  " case insensitive search
set smartcase   " If a capital letter is included, make it case-sensitive
set nohlsearch  " dont highlight search result

" Keep lines of context above and below the screen borders
set scrolloff=2

" don't beep
set visualbell
set noerrorbells

" Auto read when a file is changed on disk
set autoread

" Set textwidth for Git committing
autocmd Filetype gitcommit setlocal spell textwidth=72

" Allow vim to use a global selection buffer
set clipboard=unnamed

" Navigate split screens with Vim keybindings
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" Set filetype markdown for all .md files
autocmd BufNewFile,BufRead *.md set filetype=markdown

" Prevent Vim from changing tabs to spaces in Makefiles
autocmd FileType make setlocal noexpandtab


" Keep search matches in the middle of the window.
nnoremap n nzzzv
nnoremap N Nzzzv
