" Use Vim settings, not Vi
set nocompatible

" Detect the type of file and appropriate indentation
filetype plugin indent on

" Allow backspacing in insert mode
set backspace=indent,eol,start

" --------------
" Backup settings
" --------------
" Store backups in a central location
" Using trailing double slashes enables a feature to avoid name collisions
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//

" Keep 5000 lines of command line history
set history=5000

" Show the cursor position all the time
set ruler

" Reload files
 set autoread

" Display incomplete commands
set showcmd

" Do incremental searching
set incsearch

" Turn on syntax highlighting and highlighted search
syntax on
set hlsearch

" Show existing tab with 4 space width
set tabstop=4
" When indenting with '>', use 4 space width
set shiftwidth=4
" When pressing tab, insert 4 spaces
set expandtab

" Highlight the background past 80 characters
au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)

" Always display the status line
set laststatus=2

" show trailing whitespace chars
set list
set listchars=tab:>-,trail:.,extends:#,nbsp:.

" always set autoindenting on
set autoindent

" copy the previous indentation on autoindenting
set copyindent

" Turn on line numbers
set number

" Search Settings
set incsearch   " show search matches as you type
set ignorecase  " case insensitive search
set smartcase   " If a capital letter is included, make it case-sensitive
set nohlsearch  " dont highlight search result

" Keep lines of context above and below the screen borders
set scrolloff=2

" don't beep
set visualbell
set noerrorbells

" Auto read when a file is changed on disk
set autoread

" Set textwidth for Git committing
autocmd Filetype gitcommit setlocal spell textwidth=72

" Allow vim to use a global selection buffer
set clipboard=unnamed

" Navigate split screens with Vim keybindings
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" Set filetype markdown for all .md files
autocmd BufNewFile,BufRead *.md set filetype=markdown
