
# Set up virtualenv
if
  [ ! -d ~/.virtualenvs ]
then
  mkdir ~/.virtualenvs
fi
export WORKON_HOME=~/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

# Set up fabric8
export PATH=$PATH:~/.fabric8/bin

# Set up the Terminal for 256 colors
# Gets Vim workinger for some reason with highlighting
# May be unnecessary with coolor schemes installed
export TERM=screen-256color

alias brewclean='brew update; brew cleanup; brew cask cleanup'
alias cleanimg='docker images -qf dangling=true | xargs docker rmi'
alias cleanvol='docker volume ls -qf dangling=true | xargs docker volume rm'
alias cleancon='docker ps -qa -f exited=0 | xargs docker rm'
alias dockerdns='echo "nameserver 8.8.8.8" > /etc/resolv.conf && sudo /etc/init.d/docker restart'
alias dmachine='unset ${!DOCKER_*}'
alias dc='docker-compose'
alias dm='docker-machine'
alias denv='eval $(docker-machine env development)'
alias code='cd ~/Code/my_repos'
alias gs='git status'
alias eth='pyethapp'
alias fixaud='sudo killall coreaudiod'
