#!/bin/sh
#
###################################
#  Parlay configuration utility   #
##########################################################
#                                                        #
# Objective:                                             #
# Hack OSX for preferences, settings, and productivity.  #
#                                                        #
# Learn:                                                 #
# See documentation on DEFAULTS(1):                      #
# https://goo.gl/67dQaa                                  #
#                                                        #
##########################################################

# Set sudo for the duration of the script
sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Switch caps lock and command
# Placeholder

##########################
#    General UX/UI       #
##########################

# Disable Notification Center and remove the menu bar icon
launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null

##########################
#    Mouse / Keyboard    #
##########################

# Enable full keyboard access for all controls
# (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Enable tap to click on the Trackpad for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobaDomain com.apple.mouse.tapBehavior -int 1

# Set trackpad scroll direction to classic (flight sim style!)
defaults write -g com.apple.swipescrolldirection -bool false

# Set Mission Control access to four fingers
# Placeholder

# Enable three finger drag
# Placeholder

# Tracking speed to 'faster'
# Placeholder

# Set caps lock key to control
# Placeholder

# Set control key to caps lock
# Placeholder

# Adjust keyboard brightness in low light
# Placeholder

# Turn off keyboard lights 'faster'
# Placeholder

# Set key repeat to 'fastest'
defaults write NSGlobalDomain KeyRepeat -int 0

# Run the screensaver if we're in the bottom-left hot corner.
defaults write com.apple.dock wvous-bl-corner -int 5
defaults write com.apple.dock wvous-bl-modifier -int 0

# Set delay until key repeat to 'shortest'
# Placeholder

##########################
#        Screen         #
##########################

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Save screenshots to the desktop
defaults write com.apple.screencapture location -string "${HOME}/Documents/personal/screenshots/"

##########################
#         Dock           #
##########################

# Set Dock to auto-hide
# Placeholder

# Set Dock size to small
# Placeholder

# Set Dock position to left
# Placeholder

# Minimize applications into application icon
# Placeholder
